pipeline{

    agent any

     stages{

         stage("Build"){

                 steps{
                     echo"Building the application"
                 }

          }

         stage("Test"){

               steps{
                 echo "Running the surefire tests"
               }

         }

          stage("Deploy"){

                    steps{
                      echo "Deploying Application..."
                    }

              }


         }

    }